# Generated by Django 2.2.4 on 2019-08-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bflow_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculate',
            name='margin',
        ),
    ]
