# Generated by Django 2.2.4 on 2019-08-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bflow_web', '0002_remove_calculate_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='margin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
